### ISSUE TITLE
[BUG] Verified account

### ISSUE THREAD

**Issue by delford8** [MakerLab-Dev/MakerLab-Dev#1]
**Describe the bug**
If you have a Premium account and you refresh your profile it shows the verified icon.

**To Reproduce**
1. With a Premium account log in and go to your profile settings
2. Click on refresh button
3. You will see a verified icon next to your name

**Expected behavior**
Verified icon musn't be shown unless you have an admin account

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.4.7

**Comment by MakerLab-Dev** [comment]
I have found the bug and I'm working to fix it
Until the next pull request, the bug fix will be avalible in the beta branch in the next commit
Thanks for your report! <3

**Comment by MakerLab-Dev** [comment]
I have fixed the bug, the app with the fix is avalible in the beta branch
