### ISSUE TITLE
[BUG] Notifications not disappearing

### ISSUE THREAD

**Issue by delford8** [MakerLab-Dev/MakerLab-Dev#2]
**Describe the bug**
When all notifications are removed from the database you can still see them on the desktop app althought it says "0 notifications"

**To Reproduce**
1. Create a notification on your database
2. Refresh your desktop app to see it
3. Delete all the notifications from the database
4. Refresh again your desktop app and see that nothing was removed

**Expected behavior**
All notifications should be removed

**Screenshots**
I attached a screenshot showing it
![bug](https://user-images.githubusercontent.com/48176556/53700115-4247f180-3def-11e9-804b-59fab69e6c92.png)

**Desktop:**
 - OS: Windows 10
 - Version 1.8.4.7

**Comment by MakerLab-Dev** [comment]
Thank you for your report!
I have fixed the bug and it is avalible in the beta branch
